on:
  schedule:
    - cron: "0 5 * * 1-5"
  workflow_dispatch:

name: Milwaukee WIBRS update

jobs:
  render:
    name: Update WIBRS
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          # use Posit's CRAN mirror with precompiled binaries
          use-public-rspm: true
          
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2 # automatically sets up cache
        with:
          packages: |
            any::readr
            any::dplyr
      
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Retrieve data
        uses: nick-fields/retry@v3
        with:
          timeout_seconds: 300
          max_attempts: 3
          command: Rscript -e 'source("download-and-combine-current-wibrs.R")'
          continue_on_error: true
          
      - name: Commit data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update data